# Generated by Django 2.1.7 on 2019-02-25 22:18

import django.contrib.postgres.fields
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=255)),
                ('scientific_name', models.CharField(max_length=255)),
                ('rarity', models.CharField(choices=[('CO', 'Common'), ('SC', 'Seasonally Common'), ('RA', 'Rare')], default='CO', max_length=2)),
                ('habits', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('HI', 'Hibernates'), ('MI', 'Migrates'), ('CR', 'Cave roosts'), ('TR', 'Tree roosts')], max_length=2), blank=True, size=None)),
                ('size', django.contrib.postgres.fields.ranges.FloatRangeField()),
                ('pups', django.contrib.postgres.fields.ranges.IntegerRangeField()),
                ('risk', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('NT', 'Not threatened'), ('EN', 'Endangered'), ('TH', 'Threatened'), ('SC', 'Special concern')], max_length=2), blank=True, size=None)),
                ('risk_scope', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('ST', 'State'), ('FE', 'Federally')], max_length=2, null=True), blank=True, null=True, size=None)),
                ('bat_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.Image')),
            ],
        ),
    ]
